### ISSUE TITLE
Travis build pass despite failed tests

### ISSUE THREAD

**Issue by edouard-lopez** [pester/Pester#1214]
Despite having [tests that fail, my travis build](https://travis-ci.com/edouard-lopez/lesspass-powershell/builds/97464358) is considered valid.

### .travis.yml
```yml
os: linux
dist: trusty
sudo: required
language: minimal

addons:
  apt:
    sources:
      - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main
        key_url: https://packages.microsoft.com/keys/microsoft.asc
    packages:
      - powershell

before_script:
  - sudo pwsh -Command 'Install-Module -Name Pester -Force'
script:
  - pwsh -Command 'Get-childItem -Recurse *.test.ps1 | foreach { Invoke-Pester $_ }'

notifications:
  email: false
```

### Tests Output

```
Executing script /home/travis/build/edouard-lopez/lesspass-powershell/Validator.test.ps1
  Describing Validator
    Context Confirm opposite rules for Lowercase
error !
      [+] returns an error 133ms
      [-] contains error message 71ms
        Expected collection 'Can't have -l (--lowercase) and --no-lowercase at the same timeerror !' to contain 'Can't have -l (--lowercase) and --no-lowercase at the same time', but it was not found.
        13:             "Can't have -l (--lowercase) and --no-lowercase at the same time" | Should -BeIn $message
        at <ScriptBlock>, /home/travis/build/edouard-lopez/lesspass-powershell/Validator.test.ps1: line 13
    Context Confirm opposite rules for Uppercase
error !
      [+] returns an error 92ms
      [-] contains error message 17ms
        Expected collection 'Can't have -l (--lowercase) and --no-lowercase at the same timeerror !' to contain 'Can't have -u (--uppercase) and --no-uppercase at the same time', but it was not found.
        24:             "Can't have -u (--uppercase) and --no-uppercase at the same time" | Should -BeIn $message
        at <ScriptBlock>, /home/travis/build/edouard-lopez/lesspass-powershell/Validator.test.ps1: line 24
Tests completed in 315ms
Tests Passed: 2, Failed: 2, Skipped: 0, Pending: 0, Inconclusive: 0 
The command "pwsh -Command 'Get-childItem -Recurse *.test.ps1 | foreach { Invoke-Pester $_ }'" exited with 0.
```

### Question

How can I run test on all my tests file (`*.test.ps1`) and have the correct exit status?
