### ISSUE TITLE
HTML Code Coverage reports

### ISSUE THREAD

**Issue by FISHMANPET** [pester/Pester#1309]
Pester outputs JaCoCo XML which can be uploaded into Azure Pipelines to get code coverage statistics (though how to do it needs to be added to the readme per #872, I guess since I've done it I can look at that...).  However when you upload Code Coverage reports, a Code Coverage tab is created, with the message "Code coverage report cannot be rendered as report HTML was not found. Please verify that "Report Directory" containing an HTML report was specified when publishing code coverage."

There should be an option to output an HTML report, probably based on the JaCoCo XML file data, that can be upladed into Azure Pipelines.

I'll probably hack away at this in my spare time so you can assign it to me, but if anyone else really wants to jump in feel free

**Comment by FISHMANPET** [comment]
actually @nohwnd I see you've got a screnshot of what looks like some kind of code coverage report in the readme, it sounds like that came from VSTS, right now in Devops Pipelines this is all I can get when uploading the JaCoCo report
![image](https://user-images.githubusercontent.com/7810151/57560005-0c247200-734a-11e9-8187-3b34aebfbf02.png)

**Comment by renehernandez** [comment]
@FISHMANPET you got the assignement :)

**Comment by FISHMANPET** [comment]
Wow fell down a rabbit hole on this one...

So the Publish Code Coverage task in Azure Pipelines is in flux, but as soon as the next version of that tasks gets pushed to production (no idea how that works, 1.152.0 is in master but 1.151.2 is what's currently used in a pipeline...) it will include the ability to auto generate reports, using a tool helpfully called [ReportGenerator](https://github.com/danielpalme/ReportGenerator).  So the specific use case here, getting HTML reports into Azure Pipelines, may not be needed soon.  And I'm not sure how useful it would be to have the functionality available natively in Pester, vs just using ReportGenerator in those other build environments.  And looking at what ReportGenerator does, it's way nicer than anything I could hope to write (it's a 7 year old project, it's got a bit of a head start...)

So not sure how much value there is in working on this any farther.  If nothing else I can add some details about using ReportGenerator to the documentation when I update that.

**Comment by FISHMANPET** [comment]
There's currently a marketplace extension for Report Generator so even without the autogen included in that pipelines task you can still generate reports, here's an example for one of my org's horribly untested modules: https://dev.azure.com/umn-microsoft/UMN-Google/_build/results?buildId=23&view=codecoverage-tab

**Comment by DevOpos** [comment]
I was struggling with that issue too. The solution I chosen was to dynamically download report generator and use in azure-pipelines.yml. I had to set `HtmlInline_AzurePipelines` in `-reporttypes` parameter. :) Otherwise there was still an error "Code coverage report cannot be rendered as report HTML was not found".

Here you can see a code sample:
``` yaml
- script: |
    dotnet tool install dotnet-reportgenerator-globaltool --tool-path . 
    .\reportgenerator "-reports:$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports\ReportsCoverageResult.xml" "-targetdir:$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports" "-reporttypes:HtmlInline_AzurePipelines" 

```

**Comment by DhruvM7** [comment]
@FISHMANPET do you have a link to a PR or changelog or something which says that the Publish Code Coverage task is going to integrate ReportGenerator? I've had the task of adding it manually to my team's pipeline for Pester tests on the back burner for a while :P.

**Comment by DevOpos** [comment]
Nah, I don't have It on github. But is working well. You will need to
specify properly directories, to publish xml, covert it into html by raport
generator, and later upload results. If it's done, you will have coverage
displayed.

sob., 18 maj 2019, 17:59 użytkownik Dhruv Murarka <notifications@github.com>
napisał:

**Comment by FISHMANPET** [comment]
@DhruvM7 there's nothing super explicit you have to read behind the lines a bit.  What's currently in master for azure tasks isn't what's in production yet, I'm guessing based on build numbers that it will get released with sprint 152 but that's a total guess:
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishCodeCoverageResultsV1
If you look closely at `publishcodecoverageresults.ts` you can see some stuff about auto generating reports.

A number of issues have been opened about code coverage reports and how changes have broken them:
https://github.com/microsoft/azure-pipelines-tasks/issues/10354
https://github.com/microsoft/azure-pipelines-tasks/issues/10228
https://github.com/microsoft/azure-pipelines-tasks/issues/10212

If you dig through the issues and the pull requests and the actual code you start to get better picture but none of it has been documented in anyway which is very frustrating.

@nigurr (not sure if tagging will work since he's never contributed here) is the one doing the work on the Azure Task, he's also opened issues against ReportGenerator.

**Comment by nigurr** [comment]
@acesiddhu fyi

**Comment by pgeschwill** [comment]
@DevOpos 

I was just trying out your approach but it seems there is still something missing in my pipeline to get the report generator to run properly.

Here is the output of the task in DevOps:

##[section]Starting: CmdLine
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/d5072e52-7f81-414c-aa4a-adca9b8e6e06.sh

Welcome to .NET Core 3.0!
---------------------
SDK Version: 3.0.100

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
You can invoke the tool using the following command: reportgenerator
Tool 'dotnet-reportgenerator-globaltool' (version '4.3.6') was successfully installed.
/home/vsts/work/_temp/d5072e52-7f81-414c-aa4a-adca9b8e6e06.sh: line 2: reportgenerator: command not found
##[error]Bash exited with code '127'.
##[section]Finishing: CmdLine

I feel like it has to do with the fact that the agent runs on Ubuntu but I might be wrong on that. Does anyone else possibly have a clue?

**Comment by pgeschwill** [comment]
Adding to my previous comment:

I found a solution in this thread:
[https://github.com/microsoft/azure-pipelines-tasks/issues/10191](url)

Apparently the HTML ReportGenerator is automatically triggered in the publish task only when the pathToSources Variable is defined in the yml.

In my case, adding the variable solved the issue.

**Comment by DevOpos** [comment]
@pgeschwill I was using windows hosted agents. Looks like Ubuntu was a problem in your case. I am glad that you find the way.

**Comment by JKerens** [comment]
I was able to get it to work. Just also give the publish step the path to the source directory you ran the tests against. The script is just the example from the front page. Do yall need a documentation pull request or something? I wouldn't mind helping. 
```yaml
steps:
- powershell: |
   Install-Module Pester -MinimumVersion 4.9.0 -Scope CurrentUser -Force
   import-module pester -MinimumVersion 4.9.0
   
   Invoke-Pester -Script Pester/examples/JaCoCo/test.ps1 `
   -CodeCoverage "Pester/examples/JaCoCo/test.ps1" `
   -TestName jaja `
   -CodeCoverageOutputFile "Pester/examples/JaCoCo/coverage.xml" `
   -CodeCoverageOutputFileFormat JaCoCo
   
  displayName: 'PowerShell Script'
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from Pester/examples/JaCoCo/coverage.xml'
  inputs:
    summaryFileLocation: Pester/examples/JaCoCo/coverage.xml
    pathToSources: Pester/examples/JaCoCo
    failIfCoverageEmpty: true
```

**Comment by blacklabnz** [comment]
> I was struggling with that issue too. The solution I chosen was to dynamically download report generator and use in azure-pipelines.yml. I had to set `HtmlInline_AzurePipelines` in `-reporttypes` parameter. :) Otherwise there was still an error "Code coverage report cannot be rendered as report HTML was not found".
> 
> Here you can see a code sample:
> 
> ```yaml
> - script: |
>     dotnet tool install dotnet-reportgenerator-globaltool --tool-path . 
>     .\reportgenerator "-reports:$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports\ReportsCoverageResult.xml" "-targetdir:$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports" "-reporttypes:HtmlInline_AzurePipelines" 
> ```

faced the same issue, seems just need to install the reportgenerator using the above and genenrate html reports from the .xml coverage summary file. Once html report is generated just need to add the 'reportDirectory' property to your task.

so the combination will look like this:

```
- script: |
    dotnet tool install dotnet-reportgenerator-globaltool --tool-path . 
    .\reportgenerator "-reports:$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports\ReportsCoverageResult.xml" "-targetdir:$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports" "-reporttypes:HtmlInline_AzurePipelines"

- task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage'
        inputs:
          codeCoverageTool: JaCoCo
          summaryFileLocation: $(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports\ReportsCoverageResult.xml
          reportDirectory: $(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports
```
