### ISSUE TITLE
Additional module path on Linux not working

### ISSUE THREAD

**Issue by cathalmchale** [pester/Pester#1650]
## 1. General summary of the issue

Additional module path on Azure DevOps Linux build appears to be set correctly, but then all tests fail because it can't find the PS module being imported.

I actually use these modules in a x-platform context myself, without issue. So I'm pretty certain that it's something to do with the Pester TestRunner, rather than my modules. Also, tests pass fine on a Windows build box.

An excerpt from the build logs.

````
Using executable 'pwsh' as only only option on 'Linux'
pwsh /home/vsts/work/_tasks/Pester_cca5462b-887d-4617-bf3f-dcf0d3c622e9/10.2.3\Pester.ps1 -TestFolder /home/vsts/work/1/s/psmodules/* -resultsFile /home/vsts/work/1/s/Test-PesterDevopsAdmin.XML -run32Bit False -additionalModulePath /home/vsts/work/1/s/psmodules
TestFolder /home/vsts/work/1/s/psmodules/*

resultsFile /home/vsts/work/1/s/Test-PesterDevopsAdmin.XML
run32Bit False
additionalModulePath /home/vsts/work/1/s/psmodules

...

Running in  PowerShell

Adding additional module path [/home/vsts/work/1/s/psmodules] to $env:PSModulePath


Starting discovery in 14 files.

Discovery finished in 595ms.

##[error]Import-Module: /home/vsts/work/1/s/psmodules/Pivot.DockerAdmin/test/DockerCliScripts.Tests.ps1:3
Line |
   3 |      Import-Module Pivot.DockerAdmin
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The specified module 'Pivot.DockerAdmin' was not loaded
     | because no valid module file was found in any module directory.


##[error]Import-Module: /home/vsts/work/1/s/psmodules/Pivot.DockerAdmin/test/DockerCliScripts.Tests.ps1:3
Line |
   3 |      Import-Module Pivot.DockerAdmin
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The specified module 'Pivot.DockerAdmin' was not loaded
     | because no valid module file was found in any module directory.


[-] Pivot.DockerAdmin : Given docker run options.: When valid port bindings are specified.: Then the CLI string binds to these ports
 60ms (25ms|35ms)

 RuntimeException: No modules named 'Pivot.DockerAdmin' are currently loaded.

````

## 2. Describe Your Environment

Using Azure DevOps pipeline and the new Marketplace build step. Using a Microsoft hosted ubuntu image to run the pipeline.

## 3. Expected Behavior

Module imports successfully because the additional path has been setup correctly. And subsequently the tests pass.

## 4.Current Behavior

Additional path appears to be correct and logs as being added to the PSModulePath env var, but the tests error out because the module cannot be imported.

## 6. Context

As mentioned, I can use these modules on Linux. Where I do use them, I do so in a similar way - add to the PSModulePath env var in the Powershell session and then just call e.g. `Import-Module Pivot.DockerAdmin`.

**Comment by nohwnd** [comment]
Could you please use `Write-Host $env:PSModulePath` and `Write-Host (Get-Module -List Pivot.DockerAdmin | Out-String)` in the failing test to confirm the PSPath is correct? Pester does not modify PSPath explicitly, so I don't know why this would happen.

**Comment by cathalmchale** [comment]
Good idea @nohwnd , I should have thought to include this output in the issue to begin with.

Actually this is revealing and it looks like a bug in the Pester build step. It appears to be adding the "Additional module path", but uses the wrong path separator. Output of the Write-Host as follows:

````
In Docker CliScripts.Tests.ps1 with PSModulePath: /home/vsts/work/1/s/psmodules;/home/vsts/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules
````

Notice the semi-colon used after the "Additional module path" added by the Pester build step, whereas the other paths are separated by a colon.

Below is the relevant build yaml for inspection:

````
name: 1.$(Year:yy)$(DayOfYear)$(date:.1HHmm)

workspace:
  clean: all
  
pool:
  vmImage: 'ubuntu-18.04' # examples of other options: 'macOS-10.15', 'ubuntu-18.04', 'windows-2019'

variables:
- group: PACTFS
- name: BuildConfiguration
  value: 'release'

steps:

- task: Pester@10
  displayName: 'Pester Test Runner'
  inputs:
    scriptFolder: '$(Build.SourcesDirectory)/psmodules/*'
    resultsFile: '$(System.DefaultWorkingDirectory)/Test-PesterDevopsAdmin.XML'
    additionalModulePath: '$(Build.SourcesDirectory)/psmodules'

- task: PublishTestResults@2
  displayName: 'Publish Pester Test Results'
  inputs:
    testResultsFormat: NUnit
    testRunTitle: 'DevOps Admin results container'
  condition: succeededOrFailed()
````
