### ISSUE TITLE
Pester repo should include contributing, security, developer and supporting documentation

### ISSUE THREAD

**Issue by asears** [pester/Pester#1670]
## 1. General summary of the issue

Pester repo should include additional standard project documentation.

SECURITY.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
TEST.md or DEVELOPER.md

The .github/ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md needs to be updated to latest framework.

build.ps1 and test.ps1 should include synopsis and comments and follow standards of psscriptanalyzer.

Review licensing - should project adopt Microsoft (MIT) or updated ASF?

Templates
<https://github.com/microsoft/repo-templates/tree/main/shared>
<https://github.com/PowerShell/PSScriptAnalyzer/blob/master/PowerShellBestPractices.md>

## 6. Context

Onboarding new developers to the framework, adding new tests and actioning security issues should be documented.

**Comment by asears** [comment]
These docs require updating.

Should docs/CHANGELOG.md be in root to match other Github projects?  It could be copied to docs as part of the release steps for distribution, if required.

**Comment by asears** [comment]
Steps to updating the Github Issue template and sample yaml.

<https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository>

.github/ISSUE_TEMPLATE/config.yml

```yaml
blank_issues_enabled: false
contact_links:
  - name: Pester 5 Migration Questions Thread
    url: https://github.com/pester/Pester/issues/1218
    about: Please ask and answer questions in Powershell Slack #testing.
  - name: Pester Community Support
    url: https://powershell.slack.com/messages/C03QKTUCS/
    about: Please ask and answer questions in Powershell Slack #testing.
  - name: Pester Security
    url: https://twitter.com/nohwnd
    about: Please report security vulnerabilities here.
```
